name: SenchaApp
configs:
  Debug: debug
  Production: debug
  Release: release
packages:
  UICircularProgressRing:
    url: https://github.com/luispadron/UICircularProgressRing.git
    version: 8.0.0
options:
  deploymentTarget:
    iOS: '14.0'
targets:
  SenchaApp:
    dependencies:
      - package: UICircularProgressRing
    platform: iOS
    type: application
    sources:
      - path: SenchaApp
        excludes:
          - "**/*.framework"
          - "**/*.xcframework"
      # - R.generated.swift
    requiresObjCLinking: true
    preBuildScripts:
      - script: |
          if [ "$UPDATE_R_SWIFT" == "YES" ]; then
            $PODS_ROOT/R.swift/rswift generate $SRCROOT/R.generated.swift
          fi
        name: R.swift Run Script
        inputFiles:
          - "$TEMP_DIR/rswift-lastrun"
        outputFiles:
          - "$SRCROOT/R.generated.swift"
      - script: "${PODS_ROOT}/SwiftLint/swiftlint"
        name: Swiftlint Run Script
    # postBuildScripts:
    # - script: "${PODS_ROOT}/FirebaseCrashlytics/run"
    #   name: Run FirebaseCrashlytics Script
    #   inputFiles:
    #   - "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}"
    #   - "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}"
    info:
      path: SenchaApp/Info.plist
      properties:
        CFBundleDisplayName: 'SenchaApp'
        CFBundleShortVersionString: &Version 1.0.0
        CFBundleVersion: &BundleVersion '202103011628'
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
                UISceneStoryboardFile: Main
        UIMainStoryboardFile: Main
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsArbitraryLoadsInWebContent: true
          NSAllowsArbitraryLoadsForMedia: true
        ITSAppUsesNonExemptEncryption: false
        LSApplicationCategoryType: ''
        LSRequiresIPhoneOS: true
    settings:
      base:
        MARKETING_VERSION: *Version
        CURRENT_PROJECT_VERSION: *BundleVersion
        VERSIONING_SYSTEM: apple-generic
        PRODUCT_BUNDLE_IDENTIFIER: com.akira.matsuda.SenchaApp
        UPDATE_R_SWIFT: false
        DEVELOPMENT_TEAM: 
      configs:
        Debug: &DebugConfig
          PROVISIONING_PROFILE_SPECIFIER: com.akira.matsuda.SenchaApp Development
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          GCC_PREPROCESSOR_DEFINITIONS:
            - "$(inherited)"
            - DEBUG=1
          OTHER_SWIFT_FLAGS:
            - "$(inherited)"
            - "-D"
            - Debug
            - "-Xfrontend -debug-time-function-bodies"
        Production: &ProductionConfig
          PROVISIONING_PROFILE_SPECIFIER: com.akira.matsuda.SenchaApp Development
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          OTHER_SWIFT_FLAGS:
            - "$(inherited)"
            - "-D"
            - Production
            - "-Xfrontend -debug-time-function-bodies"
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: com.akira.matsuda.SenchaApp AppStore
          OTHER_SWIFT_FLAGS:
            - "$(inherited)"
            - "-D"
            - Release
    scheme:
      testTargets:
        - SenchaAppTests
      environmentVariables:
        DYLD_PRINT_STATISTICS: true
  SenchaAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: SenchaAppTests
    settings:
      base:
        INFOPLIST_FILE: SenchaAppTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.akira.matsuda.$(PRODUCT_NAME:rfc1034identifier)
        CODE_SIGN_STYLE: Automatic
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/SenchaApp.app/SenchaApp"
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        BUNDLE_LOADER: "$(TEST_HOST)"
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      configs:
        Debug: *DebugConfig
        Production: *ProductionConfig
        Release:
    dependencies:
      - target: SenchaApp
schemes:
  SenchaApp Production:
    build:
      targets:
        SenchaApp: all
    run:
      config: Production
